### ISSUE TITLE
Uploading Waypoint Queue Fix

### ISSUE THREAD

**Issue by ElioDiNino** [ubcuas/MissionPlanner-Scripts#8]
When in the field we were unable to queue waypoints as we kept getting an error "mission upload timeout". This needs to be looked into and fixed and see if SITL shows any of the same behaviour.

**Comment by afahimi** [comment]
Need to check during flight test for reproducability

**Comment by ElioDiNino** [comment]
Issue was not observed in our most recent test flight. We should test with more waypoints (10 would be good) to see if this arises again.

**Comment by ramjayakumar21** [comment]
#42 fixed
