### ISSUE TITLE
Investigation: `pymavlink`

### ISSUE THREAD

**Issue by i25052i** [ubcuas/MissionPlanner-Scripts#92]
### Description

Could we possible replace the use of MissionPlanner and `client.py` with `pymavlink`? 

Should we retain the capability to use MissionPlanner alongside a `pymavlink` based implementation?

**Comment by wtarit** [comment]
We created a demo, it should make the workflow/architecture simpler and easier to extend. We decided to move over the using pymavlink with mavproxy.

**Comment by wtarit** [comment]
We created a demo, it should make the workflow/architecture simpler and easier to extend. We decided to move over the using pymavlink with mavproxy.
